<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
class listStudentController extends Controller
{
    public function listsv(){
        $data = [
            [
                'id' => 1,
                'name' => 'Phạm Ngọc Tâm',
                'age' => 21,
                'mssv' => 'PD09599',
                'address' => 'Quảng Bình',
                'phone' => '0123456789',
                'school' => 'Cao Đẳng FPT Polytechnic',
                'specialized' => 'Lập trình website',
                'date' => '01/01/2023',
                'hobby' => 'Nghe nhạc, xem phim, chơi game',
            ],
            [
                'id' => 2,
                'name' => 'Nguyễn Thị Minh',
                'age' => 20,
                'mssv' => 'PD09600',
                'address' => 'Hà Nội',
                'phone' => '0987654321',
                'school' => 'Cao Đẳng FPT Polytechnic',
                'specialized' => 'Thiết kế đồ họa',
                'date' => '15/02/2023',
                'hobby' => 'Vẽ, đọc sách, nấu ăn',
            ],
            [
                'id' => 3,
                'name' => 'Trần Văn A',
                'age' => 22,
                'mssv' => 'PD09601',
                'address' => 'Hồ Chí Minh',
                'phone' => '0909123456',
                'school' => 'Cao Đẳng FPT Polytechnic',
                'specialized' => 'An ninh mạng',
                'date' => '20/03/2023',
                'hobby' => 'Thể thao, đi phượt',
            ],
            [
                'id' => 4,
                'name' => 'Lê Thị B',
                'age' => 19,
                'mssv' => 'PD09602',
                'address' => 'Đà Nẵng',
                'phone' => '0912345678',
                'school' => 'Cao Đẳng FPT Polytechnic',
                'specialized' => 'Kinh doanh online',
                'date' => '10/04/2023',
                'hobby' => 'Mua sắm, du lịch',
            ],
            [
                'id' => 5,
                'name' => 'Hoàng Văn C',
                'age' => 23,
                'mssv' => 'PD09603',
                'address' => 'Cần Thơ',
                'phone' => '0932123456',
                'school' => 'Cao Đẳng FPT Polytechnic',
                'specialized' => 'Lập trình ứng dụng di động',
                'date' => '05/05/2023',
                'hobby' => 'Lập trình, chơi game',
            ],
            [
                'id' => 6,
                'name' => 'Phan Thị D',
                'age' => 22,
                'mssv' => 'PD09604',
                'address' => 'Quảng Ninh',
                'phone' => '0943212345',
                'school' => 'Cao Đẳng FPT Polytechnic',
                'specialized' => 'Quản trị mạng',
                'date' => '25/06/2023',
                'hobby' => 'Chơi nhạc cụ, du lịch',
            ],
            [
                'id' => 7,
                'name' => 'Vũ Ngọc E',
                'age' => 20,
                'mssv' => 'PD09605',
                'address' => 'Vĩnh Long',
                'phone' => '0976512345',
                'school' => 'Cao Đẳng FPT Polytechnic',
                'specialized' => 'Lập trình web',
                'date' => '18/07/2023',
                'hobby' => 'Chơi thể thao, làm bánh',
            ],
            [
                'id' => 8,
                'name' => 'Đỗ Thị F',
                'age' => 21,
                'mssv' => 'PD09606',
                'address' => 'Hải Phòng',
                'phone' => '0987123456',
                'school' => 'Cao Đẳng FPT Polytechnic',
                'specialized' => 'Marketing',
                'date' => '10/08/2023',
                'hobby' => 'Chụp ảnh, viết lách',
            ],
            [
                'id' => 9,
                'name' => 'Nguyễn Văn G',
                'age' => 24,
                'mssv' => 'PD09607',
                'address' => 'Huế',
                'phone' => '0901345678',
                'school' => 'Cao Đẳng FPT Polytechnic',
                'specialized' => 'Thiết kế web',
                'date' => '01/09/2023',
                'hobby' => 'Xem phim, du lịch',
            ],
            [
                'id' => 10,
                'name' => 'Trần Thị H',
                'age' => 22,
                'mssv' => 'PD09608',
                'address' => 'Bình Dương',
                'phone' => '0908765432',
                'school' => 'Cao Đẳng FPT Polytechnic',
                'specialized' => 'Data Science',
                'date' => '15/10/2023',
                'hobby' => 'Đọc sách, học ngôn ngữ mới',
            ],
        ];
        return $data;
    }
}